### ISSUE TITLE
Comment tag options

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/xejs#11]
Add an option to add a "comment tag" that won't be parse into anything and will be removed on parsed file

**Comment by angrykoala** [comment]
A escape tag could also be useful

**Comment by madcampos** [comment]
Hey, may i help with this one?

**Comment by angrykoala** [comment]
@madcampos of course, the comment tag should be something optional, but the default could be something like {{# my comment }} or something like that (ideas are welcome)

**Comment by angrykoala** [comment]
requires check testing
