### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/xejs#17]
Using readme, comments,gh-pages or the github wiki, provide proper instructions on how to use xejs

**Comment by ChaudhariPrasad** [comment]
Hi @angrykoala ,

Would like to work on this.
I am new to JavaScript.

I would like play around your library to get hang of it to come up with proper instructions on how to use xejs.

Can you please share steps to give me some start like how i can create a small demo on using your library / npm module. 

Thanks,
Prasad

**Comment by angrykoala** [comment]
Hi @ChaudhariPrasad 
Thanks for your interest in this library
You can load this library as any npm library (`npm install xejs` and `var xejs=require('xerjs')` in the code)

As a demo you could check the test/main.js file. 

I'm unsure if the usage example of the readme is working right now, but you may be able to adapt it using the test.

The important part in those files is the call to xejs:

```js
xejs(file, options, args, callback);
```

Where the file is the file to parse, options are the xejs options (the default ones can be found at index.js) the args are the arguments to pass to the ejs template and finally the callback with the result.

Another working example can be found at: <https://github.com/angrykoala/yamp/blob/master/app/parsers/xejs_parser.js> where you can see several example tokens and how the arguments are passed (the function getDate)

Keep in mind that the tokens syntax will slightly change due to #4 

I hope this is enough for you to get started. Thanks again
