### ISSUE TITLE
Add Promises support

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/xejs#26]
use (apart from callbacks) promises.

Related to #16

**Comment by wingyplus** [comment]
Do you want to replace current callback api?

**Comment by wingyplus** [comment]
I think the api return Promise when user not pass the callback function. example:

```javascript
xejs(`${__dirname}/file3.md`, options, config.args).then((res) => {}, (err) => {});
```

**Comment by angrykoala** [comment]
@wingyplus not replace, but study if is reasonable to add both as interfaces for using yamp.
