### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/xejs#28]
This file should be a markdown file with instruction on the following points:
* Issues: (How, why, and when an issue should be reported, avoid duplicates)
   * Check issues before adding one or doing a PR
   * Comment issues if needed more information or planning to fix it
* Pull Request: 
   * All the PR should be done agains `dev` branch
   * All the PRs should pass the test and CI
   * Try to add the unit tests to test your changes

Also, add general information about the repo (links, author, license...) and and thanks message for contributions

**Comment by sheharyarn** [comment]
I'm on this.
